[package]
name = "arbitrage-core"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
compact_str = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
